project_id = "qxqxahgfqjctvsjddfbh"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.analyze-logs]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.generate-prompt]
verify_jwt = false

[functions.elevenlabs-tts-preview]
verify_jwt = false

[functions.create-order-payment]
verify_jwt = false